#!/bin/sh

EXTRAS_DIR="/home/eudevfin/extras"

help() {
    echo "Updates the EU-DEVFIN application to the specified version number. Can install specific artifacts (translation, extras)"
    echo "Usage $0 [install|copy-translation|copy-metadata|install-translation|install-metadata] [version_number]"
    echo "Example: $0 1.1.0"
}


if [ -n "$1" -a -n "$2" ]; then
    case "$1" in
    install)
	mvn clean install -Deudevfin.version=$2 -P install-version
    ;;
    install-translation)
	mvn install:install-file -DgroupId=org.devgateway.eudevfin -DartifactId=dim -Dversion=$2 -Dclassifier=translation -Dpackaging=jar -Dfile=$EXTRAS_DIR/dim-$2-translation.jar
	mvn install -Deudevfin.translation.version=$2 -P install-translation
    ;;
    copy-translation)
	mvn install -Deudevfin.translation.version=$2 -P copy-translation
    ;;
    copy-metadata)
	mvn install -Deudevfin.metadata.version=$2 -P copy-metadata
    ;;
    install-metadata)
	mvn install:install-file -DgroupId=org.devgateway.eudevfin -DartifactId=import-metadata -Dversion=$2 -Dclassifier=excel -Dpackaging=jar -Dfile=$EXTRAS_DIR/import-metadata-$2-excel.jar
	mvn install -Deudevfin.metadata.version=$2 -P install-metadata
    ;;
    *)
	help
    ;;
    esac
else
    help
fi




